kafka:
  bootstrapServer: localhost:9092
  bootstrap.servers: pkc-6ojrj.swedencentral.azure.confluent.cloud:9092
  input.topic.name: test
  consumer.group.name: cg-price
  sasl.mechanism: PLAIN
  sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='P57G7KMT4R7CAGSL' password='OoVwYlm1XcTp92cFSBPXZiTFOzQYgEL+RpWW63oZXdbOmShtIN7yyecVFakYDN7F';
  security.protocol: SASL_SSL
